"""Per-image Flow reference and visual data for OF Wife video."""

# Reference file names (upload these sheets in Flow)
REF_FILES = {
    "HUSBAND": "character-ref-husband.png",
    "WIFE_HOME": "character-ref-the-wife.png",
    "WIFE_CREATOR": "character-ref-the-wife-creator.png",
    "WIFE_PERFORMING": "character-ref-the-wife-performing.png",
    "WIFE_NIGHT": "character-ref-the-wife-night.png",
    "WIFE_GLAMOUR": "character-ref-the-wife-glamour.png",
    "NEIGHBOR": "character-ref-neighbor.png",
    "MOTHER_IN_LAW": "character-ref-mother-in-law.png",
    "FATHER_IN_LAW": "character-ref-father-in-law.png",
    "COWORKER": "character-ref-coworker.png",
    "HR_MANAGER": "character-ref-hr-manager.png",
}

REF_ROLES = {
    "HUSBAND": "POV protagonist / tired husband age 32",
    "WIFE_HOME": "THE WIFE home version / cream sweater casual",
    "WIFE_CREATOR": "THE WIFE creator version / crop top ring light",
    "WIFE_PERFORMING": "THE WIFE performing version / camera pose",
    "WIFE_NIGHT": "THE WIFE night secret version / tank top office",
    "WIFE_GLAMOUR": "THE WIFE glamour version / halter crop 2000s look",
    "NEIGHBOR": "Suburban neighbor dad",
    "MOTHER_IN_LAW": "Wife's mother / family dinner",
    "FATHER_IN_LAW": "Wife's father / ashamed at dinner",
    "COWORKER": "Office coworker with phone",
    "HR_MANAGER": "HR manager conference room",
}

# Per scene: wife version label for lot header + list of (refs, visual) per image
# refs: list of keys from REF_FILES or ["NONE"]
SCENE_LOT_META = {
    1: {
        "wife_version": "WIFE_CREATOR + WIFE_GLAMOUR",
        "mood": "Fast chaotic hook. Marriage collapsing. Phone, money, secrets. Rhythm: 1-2 sec/image",
        "images": [
            (["HUSBAND"], "Close-up HUSBAND hand holding smartphone with many notification bubbles, shocked tired eyes reflected in screen glow, kitchen background blur."),
            (["NONE"], "Ring light glowing behind a closed home office door, warm light leaking through crack, suspenseful hallway, no characters."),
            (["NONE"], "Kitchen table covered with stacks of cash bills, wedding photo on wall in background, dramatic overhead angle, no people."),
            (["NEIGHBOR"], "NEIGHBOR on front porch staring at HUSBAND with judgmental curious expression, suburban house behind, awkward tension."),
            (["NONE"], "Open shipping box on kitchen counter with folded outfits visible, packing materials scattered, empty room."),
            (["WIFE_CREATOR"], "WIFE_CREATOR turning laptop screen away from camera, defensive body language, black crop top, guilty sideways glance."),
            (["NONE"], "Home office door locked from inside, brass handle close-up, muffled light under door."),
            (["HUSBAND"], "HUSBAND knocking on locked office door, frustrated raised fist, blue shirt wrinkled, hallway perspective."),
            (["NONE"], "Laptop on desk showing blurred colorful subscription-style app icon, no readable text, ring light reflection."),
            (["HUSBAND", "WIFE_GLAMOUR"], "HUSBAND and WIFE_GLAMOUR arguing in hallway, both gesturing, tense faces, marriage crisis energy."),
        ],
    },
    2: {
        "wife_version": "WIFE_GLAMOUR",
        "mood": "Emotional peak of hook. Fear, tears, silence. Rhythm: 1-2 sec/image",
        "images": [
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR stepping backward with hands raised defensively, afraid expression, tears forming."),
            (["HUSBAND"], "Close-up HUSBAND trembling hands in foreground, wedding band visible, shallow depth of field."),
            (["NONE"], "Banking app deposit notification on phone screen showing large number, no readable text labels, green accent only."),
            (["NONE"], "Wedding photo frame on wall showing happy couple silhouette, contrast with present chaos."),
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR crying, tears on cheeks, mascara slightly smudged, broken expression."),
            (["HUSBAND"], "HUSBAND standing completely still in kitchen, frozen shock pose, hollow stare."),
            (["NONE"], "Door slamming shut motion lines, hallway perspective, dramatic impact."),
            (["NONE"], "Empty quiet living room, still furniture, heavy silence atmosphere."),
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR reaching both hands toward viewer, pleading gesture, tearful eyes."),
            (["HUSBAND", "WIFE_GLAMOUR"], "Wide shot marriage breaking apart metaphor: HUSBAND on left WIFE_GLAMOUR on right, distance between them growing."),
        ],
    },
    3: {
        "wife_version": "WIFE_GLAMOUR then WIFE_HOME",
        "mood": "Hook climax then rewind. Line, black screen, 24 hours earlier. Rhythm: 1-2 sec/image",
        "images": [
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR finally making eye contact, red rimmed eyes, vulnerable close-up face."),
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR mouth opening to speak, extreme close-up lips and eyes, emotional confession moment."),
            (["HUSBAND"], "HUSBAND looking down unable to meet her eyes, ashamed defeated posture, POV husband angle."),
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR whispering, soft intimate framing, painful confession energy."),
            (["WIFE_GLAMOUR", "HUSBAND"], "WIFE_GLAMOUR saying key line, HUSBAND recoiling backward, shockwave between them."),
            (["HUSBAND"], "HUSBAND stepping back like struck, hand on chest, devastation on face."),
            (["NONE"], "Full black screen image, pure darkness, cinematic pause frame."),
            (["NONE"], "Simple sunrise over peaceful suburban house exterior, calm morning, rewind visual."),
            (["NONE"], "Peaceful bright kitchen morning light through window, empty calm before storm."),
            (["NONE"], "Stylized title card composition: suburban house and couple silhouette, space for title in editing, no readable text on artwork."),
        ],
    },
    4: {
        "wife_version": "WIFE_HOME",
        "mood": "Warm normal marriage. Act 1 setup. Rhythm: 3-4 sec/image",
        "images": [
            (["NONE"], "Sunlit kitchen morning, warm golden light through window, coffee mugs on counter."),
            (["WIFE_HOME"], "WIFE_HOME pouring coffee into mug, loving smile, cream sweater, domestic warmth."),
            (["HUSBAND", "WIFE_HOME"], "HUSBAND kissing WIFE_HOME goodbye at door, loving embrace, before work routine."),
            (["HUSBAND", "WIFE_HOME"], "Happy couple memory framing: both smiling, three years marriage bliss."),
            (["HUSBAND"], "HUSBAND at office desk buried in paperwork, tired expression, stacks of documents."),
            (["HUSBAND"], "HUSBAND eating alone at office desk, missed dinner, sad clock on wall."),
            (["HUSBAND", "WIFE_HOME"], "HUSBAND arriving home, WIFE_HOME welcoming him at door with warm smile."),
            (["WIFE_HOME"], "WIFE_HOME smiling over laptop at kitchen table, excited secret energy, cream sweater."),
            (["WIFE_HOME", "HUSBAND"], "WIFE_HOME telling news to HUSBAND, animated happy gesture, laptop open."),
            (["HUSBAND"], "HUSBAND responding positively, supportive smile, thumbs up gesture."),
            (["WIFE_HOME"], "WIFE_HOME proud hopeful expression, dreaming of side hustle success."),
        ],
    },
    5: {
        "wife_version": "WIFE_HOME",
        "mood": "Side hustle begins. Distance growing quietly. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND", "WIFE_HOME"], "HUSBAND asking curious question, WIFE_HOME evasive light smile."),
            (["WIFE_HOME"], "WIFE_HOME casual dismissive hand wave, content creation excuse, laptop in lap."),
            (["NONE"], "Calendar pages flipping montage, weeks passing, time lapse visual."),
            (["HUSBAND"], "HUSBAND working late at office, dark windows, exhausted at computer."),
            (["WIFE_HOME"], "WIFE_HOME alone behind closed door with laptop glow, HUSBAND absent."),
            (["NONE"], "Small package on front porch, delivery box, suburban doorstep."),
            (["WIFE_HOME"], "WIFE_HOME quickly grabbing package before HUSBAND sees label."),
            (["HUSBAND", "WIFE_HOME"], "Cold reheated dinner scene, WIFE_HOME distracted on phone, HUSBAND tired."),
            (["WIFE_HOME"], "WIFE_HOME mentioning good numbers, secretive pleased smile."),
            (["HUSBAND"], "HUSBAND too tired to ask questions, rubbing eyes at table."),
            (["NONE"], "Split screen normal life continuing, routine settling, subtle unease."),
        ],
    },
    6: {
        "wife_version": "WIFE_HOME",
        "mood": "First clue ignored. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND"], "HUSBAND sorting mail Saturday morning at kitchen counter."),
            (["NONE"], "Receipt falling from mail stack, ring light equipment sketch visible, no readable text."),
            (["NONE"], "Close-up ring light and studio kit icons on receipt paper, no prices readable."),
            (["HUSBAND", "WIFE_HOME"], "HUSBAND showing receipt to WIFE_HOME at breakfast, confused half-smile."),
            (["WIFE_HOME"], "WIFE_HOME answering too quickly, nervous smile, side hustle excuse."),
            (["WIFE_HOME"], "WIFE_HOME changing subject, pointing at calendar weekend plans."),
            (["HUSBAND"], "HUSBAND wanting to believe her, internal conflict expression."),
            (["WIFE_HOME"], "WIFE_HOME seemingly happy at table, hiding truth beneath smile."),
            (["HUSBAND"], "HUSBAND folding receipt and discarding it, letting clue go."),
            (["HUSBAND", "WIFE_HOME"], "WIFE_HOME squeezing HUSBAND hand across table, false normalcy."),
            (["NONE"], "Peaceful suburban morning continuing, clue vanishes into normal day."),
        ],
    },
    7: {
        "wife_version": "WIFE_CREATOR",
        "mood": "Packages escalate. Husband suspicious. Rhythm: 3-4 sec/image",
        "images": [
            (["NONE"], "Multiple delivery boxes stacked in hallway, every other day pattern."),
            (["NONE"], "Boxes open showing outfits makeup softbox lights, content creator supplies."),
            (["NEIGHBOR"], "Delivery driver smiling at WIFE_CREATOR, friendly wave, have a great shoot energy."),
            (["NEIGHBOR", "HUSBAND"], "NEIGHBOR saying shoot comment, HUSBAND freezing on porch with keys."),
            (["HUSBAND"], "HUSBAND frozen shocked on porch holding keys, processing comment."),
            (["WIFE_CREATOR"], "WIFE_CREATOR laughing off influencer mail excuse, stacking boxes."),
            (["WIFE_CREATOR"], "WIFE_CREATOR quickly stacking boxes inside home office."),
            (["NONE"], "Office door closing faster, HUSBAND walking past in background."),
            (["HUSBAND"], "HUSBAND noticing pattern but staying silent, worried brow."),
            (["HUSBAND"], "HUSBAND uneasy expression, something wrong he cannot name."),
            (["NONE"], "More packages arriving like warnings, doorstep pile growing."),
        ],
    },
    8: {
        "wife_version": "WIFE_HOME + WIFE_NIGHT",
        "mood": "Phone secrecy. 2am office light. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND", "WIFE_HOME"], "Dinner table, phone vibrating, WIFE_HOME flipping it face down."),
            (["WIFE_HOME"], "WIFE_HOME hiding phone screen, fake casual expression."),
            (["HUSBAND", "WIFE_HOME"], "HUSBAND asking who texts, WIFE_HOME dismissive spam excuse."),
            (["WIFE_HOME"], "WIFE_HOME smile not reaching eyes, lying at dinner."),
            (["HUSBAND"], "HUSBAND waking at 2am alone in empty bed, worried."),
            (["NONE"], "Light bleeding under office door down dark hallway."),
            (["WIFE_NIGHT"], "Silhouette WIFE_NIGHT voice behind door, unfamiliar tone, secretive."),
            (["HUSBAND"], "HUSBAND at locked door, hand on handle, conflicted."),
            (["HUSBAND"], "HUSBAND returning to bed without knocking, defeated posture."),
            (["WIFE_NIGHT"], "WIFE_NIGHT slipping into bedroom at dawn, perfume scent lines, guilty."),
            (["HUSBAND"], "HUSBAND pretending to sleep, eyes barely open, fear."),
        ],
    },
    9: {
        "wife_version": "WIFE_CREATOR",
        "mood": "Money appears. App icon glimpse. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND"], "HUSBAND brushing teeth, phone notification appearing in mirror reflection."),
            (["NONE"], "Bank deposit notification large amount, numbers blurred no readable text."),
            (["HUSBAND"], "HUSBAND staring at phone number in disbelief."),
            (["HUSBAND", "WIFE_CREATOR"], "WIFE_CREATOR grinning over HUSBAND shoulder, proud secretive."),
            (["WIFE_CREATOR"], "WIFE_CREATOR saying hustle worked, kissing cheek, confident."),
            (["HUSBAND", "WIFE_CREATOR"], "HUSBAND wanting to celebrate, WIFE_CREATOR emotionally distant."),
            (["HUSBAND", "WIFE_CREATOR"], "HUSBAND asking where money came from, calm voice."),
            (["WIFE_CREATOR"], "WIFE_CREATOR smooth rehearsed answer about brand deals."),
            (["WIFE_CREATOR"], "Notification vanishing from WIFE_CREATOR phone screen too fast."),
            (["HUSBAND"], "HUSBAND catching app icon color before screen locks."),
            (["HUSBAND"], "HUSBAND stomach drop expression, WIFE_CREATOR unaware."),
        ],
    },
    10: {
        "wife_version": "WIFE_NIGHT",
        "mood": "Discovery day begins. Spare key. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND"], "HUSBAND tense morning, everything about to change atmosphere."),
            (["WIFE_NIGHT"], "Locked office door, WIFE_NIGHT voice behind wood softer than usual."),
            (["WIFE_NIGHT"], "Close door with WIFE_NIGHT silhouette, secretive tone visual."),
            (["HUSBAND", "WIFE_HOME"], "Contrast memory WIFE_HOME at breakfast vs present secret voice."),
            (["HUSBAND"], "HUSBAND searching hallway drawer for spare key."),
            (["NONE"], "Brass spare key cold in HUSBAND palm close-up."),
            (["NONE"], "Camera shutter sound effect lines from behind door."),
            (["HUSBAND"], "HUSBAND conflicted should knock wait trust marriage."),
            (["HUSBAND"], "HUSBAND sliding key into lock turning slowly."),
            (["HUSBAND"], "Door opening onto shocking new reality, light burst."),
            (["HUSBAND"], "HUSBAND trembling hand on door handle."),
        ],
    },
    11: {
        "wife_version": "WIFE_PERFORMING",
        "mood": "Ring light reveal. Profile on screen. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND", "WIFE_PERFORMING"], "Ring light blinding HUSBAND as door opens, WIFE_PERFORMING at desk."),
            (["NONE"], "Laptop open on desk like trial evidence, dramatic angle."),
            (["NONE"], "Profile page on laptop blurred photos subscriber count shapes, no readable text."),
            (["NONE"], "Suggestive but clothed photo grid silhouettes on screen, thousands of subscribers visual."),
            (["NONE"], "Subscriber count climbing graphic shapes, no numbers readable."),
            (["WIFE_PERFORMING"], "WIFE_PERFORMING spinning around color draining from face caught."),
            (["HUSBAND"], "HUSBAND heart stopping shock, hand on chest."),
            (["HUSBAND", "WIFE_PERFORMING"], "Both frozen silent, words would make permanent."),
            (["NONE"], "Blinking cursor on laptop screen waiting reaction."),
            (["HUSBAND"], "HUSBAND connecting clues packages money door in mind montage."),
            (["HUSBAND"], "All past weeks clues crashing into focus expression."),
        ],
    },
    12: {
        "wife_version": "WIFE_PERFORMING",
        "mood": "OnlyFans revelation. Silence worse than yelling. Rhythm: 3-4 sec/image",
        "images": [
            (["WIFE_PERFORMING"], "WIFE_PERFORMING saying words screen already did, confession pose."),
            (["WIFE_PERFORMING"], "WIFE_PERFORMING verbal confession moment, ashamed proud mix."),
            (["HUSBAND", "WIFE_PERFORMING"], "HUSBAND not yelling, devastating silence between couple."),
            (["HUSBAND"], "HUSBAND whispering how long, broken voice."),
            (["WIFE_PERFORMING"], "WIFE_PERFORMING answering three months, guilty eyes."),
            (["HUSBAND"], "HUSBAND processing three months of lies montage face."),
            (["HUSBAND"], "HUSBAND asking why not told, hurt small voice."),
            (["WIFE_PERFORMING"], "WIFE_PERFORMING tears forming, was going to tell excuse."),
            (["WIFE_PERFORMING"], "WIFE_PERFORMING needed right moment plea."),
            (["HUSBAND"], "HUSBAND realizing right moment never came, worked late blame."),
            (["HUSBAND", "WIFE_PERFORMING"], "Discovery is beginning not end, new chapter dread."),
        ],
    },
    13: {
        "wife_version": "WIFE_GLAMOUR",
        "mood": "Neighbor and gossip. Public shame. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND"], "HUSBAND walking outside walls cannot hold pain, need air."),
            (["NEIGHBOR"], "NEIGHBOR watering lawn ordinary afternoon suburban."),
            (["NEIGHBOR", "HUSBAND"], "NEIGHBOR grin saying saw wife online, HUSBAND frozen."),
            (["NEIGHBOR"], "NEIGHBOR congrats on success friendly cruel comment."),
            (["NEIGHBOR", "HUSBAND"], "NEIGHBOR laughing, HUSBAND not laughing world splitting."),
            (["NONE"], "Word traveling neighborhood gossip visual, whisper lines."),
            (["NONE"], "Grocery store whispers behind HUSBAND in line."),
            (["HUSBAND"], "Group chat screenshot on phone, HUSBAND deleting too late."),
            (["HUSBAND"], "HUSBAND deleting message knowing too late."),
            (["WIFE_GLAMOUR"], "Inside WIFE_GLAMOUR editing content acting normal."),
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR pretending world did not shift."),
        ],
    },
    14: {
        "wife_version": "WIFE_GLAMOUR (absent at work)",
        "mood": "Workplace humiliation. HR threat. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND"], "HUSBAND walking into office like spotlight on him."),
            (["COWORKER", "HUSBAND"], "COWORKER showing phone smirk at HUSBAND."),
            (["COWORKER"], "COWORKER loud question is this your wife, break room."),
            (["COWORKER"], "Laughter spreading break room, HUSBAND humiliated center."),
            (["HR_MANAGER"], "HR_MANAGER calling HUSBAND to glass conference room."),
            (["HR_MANAGER", "HUSBAND"], "HR_MANAGER discussing situation stern neutral faces."),
            (["HR_MANAGER"], "Promotion frozen document clipboard visual."),
            (["HUSBAND"], "HUSBAND driving home gripping steering wheel white knuckles."),
            (["HUSBAND"], "Anger replacing shock on HUSBAND face first time."),
            (["HUSBAND"], "Destroying everything outside walls realization."),
        ],
    },
    15: {
        "wife_version": "WIFE_GLAMOUR",
        "mood": "Family dinner trial. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND", "WIFE_GLAMOUR", "MOTHER_IN_LAW", "FATHER_IN_LAW"], "Family dinner table wide, tension thick air."),
            (["MOTHER_IN_LAW"], "MOTHER_IN_LAW smiling too wide across table."),
            (["MOTHER_IN_LAW", "WIFE_GLAMOUR"], "MOTHER_IN_LAW slow online business comment, everyone understands."),
            (["HUSBAND", "MOTHER_IN_LAW", "FATHER_IN_LAW"], "Everyone at table understands unspoken meaning."),
            (["FATHER_IN_LAW"], "FATHER_IN_LAW avoiding eye contact looking down."),
            (["HUSBAND", "WIFE_GLAMOUR"], "WIFE_GLAMOUR squeezing HUSBAND hand under tablecloth."),
            (["HUSBAND"], "HUSBAND eating without tasting shame."),
            (["HUSBAND", "WIFE_GLAMOUR"], "In car afterward HUSBAND finally speaking anger."),
            (["HUSBAND"], "HUSBAND saying destroying us through windshield stare."),
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR answering let me explain steady voice."),
        ],
    },
    16: {
        "wife_version": "WIFE_CREATOR",
        "mood": "Ultimatum to stop. Suitcase. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND", "WIFE_CREATOR"], "HUSBAND demanding she stop immediately that night."),
            (["HUSBAND"], "HUSBAND commanding delete everything walk away."),
            (["WIFE_CREATOR"], "WIFE_CREATOR shaking head terrifying certainty refuse."),
            (["WIFE_CREATOR"], "WIFE_CREATOR cannot not yet not finished plea."),
            (["HUSBAND", "WIFE_CREATOR"], "HUSBAND so money matters more than us accusation."),
            (["WIFE_CREATOR"], "WIFE_CREATOR going quiet silence hurts more."),
            (["HUSBAND"], "HUSBAND pulling honeymoon suitcase from closet."),
            (["WIFE_CREATOR"], "WIFE_CREATOR watching doorway held back tears."),
            (["HUSBAND", "WIFE_CREATOR"], "WIFE_CREATOR asking where going, HUSBAND packing."),
            (["HUSBAND"], "HUSBAND anywhere but here answer, suitcase in hand."),
        ],
    },
    17: {
        "wife_version": "WIFE_HOME",
        "mood": "Hidden bank statement discovered. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND"], "HUSBAND searching dresser for passport leaving possible."),
            (["NONE"], "Bank statement beneath folded shirts hidden discovery."),
            (["NONE"], "Past due notices red highlights mortgage visual no readable text."),
            (["NONE"], "Four months missed mortgage payments graphic."),
            (["NONE"], "Late fees stacking second debt visual charts."),
            (["HUSBAND"], "HUSBAND never knew she handled bills trusted."),
            (["HUSBAND"], "HUSBAND hands cold reading numbers blur."),
            (["HUSBAND"], "HUSBAND whispering about to lose everything."),
            (["WIFE_HOME"], "WIFE_HOME appearing behind HUSBAND silently caught."),
            (["WIFE_HOME", "HUSBAND"], "WIFE_HOME please let me explain softly."),
        ],
    },
    18: {
        "wife_version": "WIFE_HOME",
        "mood": "Mortgage secret revealed. Grand twist. Rhythm: 3-4 sec/image",
        "images": [
            (["WIFE_HOME"], "WIFE_HOME sitting bed legs won't hold confession pose."),
            (["WIFE_HOME"], "WIFE_HOME lost job eight weeks before starting."),
            (["WIFE_HOME"], "WIFE_HOME found foreclosure letters in mail."),
            (["WIFE_HOME"], "WIFE_HOME three months until lose house plea."),
            (["WIFE_HOME"], "WIFE_HOME panicked searched anything fast."),
            (["WIFE_HOME"], "WIFE_HOME OnlyFans only door opened quickly."),
            (["WIFE_HOME"], "WIFE_HOME every dollar went to mortgage."),
            (["WIFE_HOME"], "WIFE_HOME going to tell after one more month."),
            (["WIFE_HOME", "HUSBAND"], "WIFE_HOME would you have let me question cuts deep."),
            (["HUSBAND"], "HUSBAND no answer unsure of truth."),
        ],
    },
    19: {
        "wife_version": "WIFE_HOME (absent)",
        "mood": "Considering leaving. Two paths. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND"], "Half packed suitcase by door question without answer."),
            (["HUSBAND"], "HUSBAND staring wedding photo barely recognize smiles."),
            (["HUSBAND"], "Phone flooding messages every direction."),
            (["NONE"], "Montage icons coworkers neighbors family wanting answers."),
            (["HUSBAND"], "Career reputation home hanging fragile balance."),
            (["HUSBAND"], "Two paths split neither looks clean visual fork."),
            (["NONE"], "Open front door escape path bright outside."),
            (["NONE"], "Bedroom light harder fight path warm glow."),
            (["HUSBAND"], "Yesterday trusted everything without asking memory."),
            (["HUSBAND"], "That version of HUSBAND gone now hollow."),
        ],
    },
    20: {
        "wife_version": "WIFE_HOME",
        "mood": "She explains debt progress. Moral gray. Rhythm: 3-4 sec/image",
        "images": [
            (["WIFE_HOME"], "WIFE_HOME spreading papers across kitchen table evidence."),
            (["NONE"], "Seventy percent debt paid charts visual no readable numbers."),
            (["NONE"], "Six more weeks to save house calendar visual."),
            (["WIFE_HOME", "HUSBAND"], "WIFE_HOME never cheated firm eye contact."),
            (["WIFE_HOME"], "WIFE_HOME not once not anyone reassurance."),
            (["HUSBAND", "WIFE_HOME"], "HUSBAND you should have told me grief."),
            (["WIFE_HOME", "HUSBAND"], "WIFE_HOME would you have listened challenge."),
            (["WIFE_HOME"], "Or stop before saved anything counter argument."),
            (["HUSBAND", "WIFE_HOME"], "Silence fills room neither wins."),
            (["HUSBAND", "WIFE_HOME"], "Both right both wrong unbearable truth."),
        ],
    },
    21: {
        "wife_version": "WIFE_PERFORMING + WIFE_GLAMOUR",
        "mood": "Return to hook moment. Full circle. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND", "WIFE_GLAMOUR"], "Argument returns same hallway hours later."),
            (["NONE"], "Same locked door same tension crackling air."),
            (["HUSBAND"], "Phone buzz another notification HUSBAND dreads."),
            (["NONE"], "Cash still on kitchen table from deposits."),
            (["NEIGHBOR"], "NEIGHBOR porch light clicks on world watching."),
            (["HUSBAND"], "HUSBAND understands cold open now living inside it."),
            (["HUSBAND"], "Every image from start makes painful sense."),
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR reaching toward HUSBAND tears cheeks."),
            (["HUSBAND"], "HUSBAND hands shaking rage or grief unknown."),
            (["WIFE_GLAMOUR", "HUSBAND"], "WIFE_GLAMOUR never wanted you find out like this line."),
        ],
    },
    22: {
        "wife_version": "WIFE_HOME",
        "mood": "Ultimatum morning. Two options. Rhythm: 3-4 sec/image",
        "images": [
            (["HUSBAND"], "Morning after night on couch gray quiet."),
            (["WIFE_HOME", "HUSBAND"], "WIFE_HOME setting coffee peace offering trap."),
            (["WIFE_HOME"], "WIFE_HOME will stop today if you need."),
            (["WIFE_HOME"], "WIFE_HOME lose house six weeks warning."),
            (["WIFE_HOME"], "WIFE_HOME finish six weeks then done forever choice."),
            (["HUSBAND", "WIFE_HOME"], "Two options neither clean on table between mugs."),
            (["HUSBAND"], "HUSBAND looking wedding photo wall."),
            (["HUSBAND"], "Then door suitcase still half packed."),
            (["HUSBAND"], "Career already damaged cannot undo."),
            (["HUSBAND", "WIFE_HOME"], "Marriage might salvageable maybe unsure."),
        ],
    },
    23: {
        "wife_version": "WIFE_GLAMOUR",
        "mood": "Final moral lines. Debate ending. Rhythm: 3-4 sec/image",
        "images": [
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR stands calmly no more crying."),
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR without this money quiet line."),
            (["WIFE_GLAMOUR"], "We lose the house weight of words."),
            (["HUSBAND", "WIFE_GLAMOUR"], "HUSBAND look up everything collides once."),
            (["HUSBAND"], "Trust pride fear love shame internal storm face."),
            (["HUSBAND"], "HUSBAND opening mouth cannot take back."),
            (["HUSBAND", "WIFE_GLAMOUR"], "HUSBAND maybe not physically devastating line."),
            (["WIFE_GLAMOUR"], "WIFE_GLAMOUR steps back like hit never moved."),
            (["HUSBAND", "WIFE_GLAMOUR"], "Neither explains what that means both understand."),
            (["NONE"], "Question hangs video refuses answer empty space."),
        ],
    },
    24: {
        "wife_version": "WIFE_HOME",
        "mood": "Black screen ending. Open debate. Rhythm: 3-5 sec/image",
        "images": [
            (["HUSBAND", "WIFE_HOME"], "Kitchen goes silent refrigerator hum."),
            (["HUSBAND", "WIFE_HOME"], "Coffee steam rises wall between them."),
            (["WIFE_HOME"], "WIFE_HOME does not move accepting answer."),
            (["HUSBAND"], "HUSBAND does not move leaving staying impossible."),
            (["NONE"], "No music swells empty cinematic space."),
            (["NONE"], "No narrator explains moral void."),
            (["NONE"], "No easy answer appears comfort denied."),
            (["NONE"], "Full black screen frame pure darkness."),
            (["NONE"], "Hold darkness weight settling pause."),
            (["NONE"], "Implicit question what would you have done, empty frame."),
        ],
    },
}
